name: Testing wip

on:
  pull_request:
    branches: [ "master", "release/*" ]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  testing:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode and create secret key
        run: |
          echo ${{ secrets.SIGNING_KEY_SECRET }} | base64 --decode > secret_key.gpg
          ls -l secret_key.gpg
          pwd
          echo ${{ secrets.SIGNING_KEY_SECRET }}
          pwd
          base64 secret_key.gpg | echo

      - name: Set permissions for GPG key
        run: chmod 600 secret_key.gpg