name: Unit tests

on:
  pull_request:
    branches: [ "master", "release/*" ]
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execution permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew :client:cleanTestDebugUnitTest :client:testDebugUnitTest --tests "org.apptank.horus.client.*" --no-configuration-cache
