name: Validate Release Branch

on:
  pull_request:
    branches:
      - release/*
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract release version from branch name
        id: extract_branch_version
        run: |
          echo "Branch: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" =~ release/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "branch_version=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "The branch name is not in the correct format (release/X.Y.Z)."
            exit 1
          fi

      - name: Extract version from gradle.properties
        id: extract_gradle_version
        run: |
          gradle_version=$(grep 'lib.version' gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          echo "gradle_version=${gradle_version}" >> $GITHUB_ENV

      - name: Validate branch version matches gradle version
        id: validate_versions
        run: |
          if [ "${{ env.branch_version }}" != "${{ env.gradle_version }}" ]; then
            echo "The branch version (${ env.branch_version }) does not match the version in gradle.properties (${ env.gradle_version })."
            exit 1
          else
            echo "Branch version matches gradle.properties version."
          fi

      - name: Notify success
        if: success()
        run: echo "Validation completed successfully. The branch version matches the gradle.properties version."